apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mpak.fullname" . }}
  namespace: {{ include "mpak.namespace" . }}
  labels:
    {{- include "mpak.labels" . | nindent 4 }}
data:
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  S3_REGION: {{ .Values.config.s3Region | quote }}
  {{- range $key, $value := .Values.registry.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
